ThirdExamDotNet/Controllers/ClassroomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThirdExamDotNet.Context;
using ThirdExamDotNet.Models;

namespace ThirdExamDotNet.Controllers
{
    public class ClassroomsController : Controller
    {
        private readonly ContextDb _context;

        public ClassroomsController(ContextDb context)
        {
            _context = context;
        }

        // GET: Classrooms
        public async Task<IActionResult> Index()
        {
            var contextDb = _context.Classrooms.Include(c => c.Instructor).Include(c => c.Tower);
            return View(await contextDb.ToListAsync());
        }

        // GET: Classrooms/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Classrooms == null)
            {
                return NotFound();
            }

            var classroom = await _context.Classrooms
                .Include(c => c.Instructor)
                .Include(c => c.Tower)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (classroom == null)
            {
                return NotFound();
            }

            return View(classroom);
        }

        // GET: Classrooms/Create
        public IActionResult Create()
        {
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName");
            ViewData["TowerId"] = new SelectList(_context.Towers, "Id", "Zone");
            return View();
        }

        // POST: Classrooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Floor,TowerId,InstructorId")] Classroom classroom)
        {
            if (ModelState.IsValid)
            {
                classroom.Id = Guid.NewGuid();
                _context.Add(classroom);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName", classroom.InstructorId);
            ViewData["TowerId"] = new SelectList(_context.Towers, "Id", "Zone", classroom.TowerId);
            return View(classroom);
        }

        // GET: Classrooms/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Classrooms == null)
            {
                return NotFound();
            }

            var classroom = await _context.Classrooms.FindAsync(id);
            if (classroom == null)
            {
                return NotFound();
            }
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName", classroom.InstructorId);
            ViewData["TowerId"] = new SelectList(_context.Towers, "Id", "Zone", classroom.TowerId);
            return View(classroom);
        }

        // POST: Classrooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Code,Floor,TowerId,InstructorId")] Classroom classroom)
        {
            if (id != classroom.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(classroom);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassroomExists(classroom.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstructorId"] = new SelectList(_context.Instructors, "Id", "FullName", classroom.InstructorId);
            ViewData["TowerId"] = new SelectList(_context.Towers, "Id", "Zone", classroom.TowerId);
            return View(classroom);
        }

        // GET: Classrooms/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Classrooms == null)
            {
                return NotFound();
            }

            var classroom = await _context.Classrooms
                .Include(c => c.Instructor)
                .Include(c => c.Tower)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (classroom == null)
            {
                return NotFound();
            }

            return View(classroom);
        }

        // POST: Classrooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Classrooms == null)
            {
                return Problem("Entity set 'ContextDb.Classrooms'  is null.");
            }
            var classroom = await _context.Classrooms.FindAsync(id);
            if (classroom != null)
            {
                _context.Classrooms.Remove(classroom);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassroomExists(Guid id)
        {
          return (_context.Classrooms?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ThirdExamDotNet/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThirdExamDotNet.Context;
using ThirdExamDotNet.Models;

namespace ThirdExamDotNet.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ContextDb _context;

        public StudentsController(ContextDb context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var contextDb = _context.Students.Include(s => s.Classroom).Include(s => s.StudyProgram);
            return View(await contextDb.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.Classroom)
                .Include(s => s.StudyProgram)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "Id", "Code");
            ViewData["StudyProgramId"] = new SelectList(_context.StudyPrograms, "Id", "Name");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Document,FullName,Email,Phone,Address,StudyProgramId,ClassroomId")] Student student)
        {
            if (ModelState.IsValid)
            {
                student.Id = Guid.NewGuid();
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "Id", "Code", student.ClassroomId);
            ViewData["StudyProgramId"] = new SelectList(_context.StudyPrograms, "Id", "Name", student.StudyProgramId);
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "Id", "Code", student.ClassroomId);
            ViewData["StudyProgramId"] = new SelectList(_context.StudyPrograms, "Id", "Name", student.StudyProgramId);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Document,FullName,Email,Phone,Address,StudyProgramId,ClassroomId")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassroomId"] = new SelectList(_context.Classrooms, "Id", "Code", student.ClassroomId);
            ViewData["StudyProgramId"] = new SelectList(_context.StudyPrograms, "Id", "Name", student.StudyProgramId);
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.Classroom)
                .Include(s => s.StudyProgram)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'ContextDb.Students'  is null.");
            }
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(Guid id)
        {
          return (_context.Students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ThirdExamDotNet/Controllers/TowersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThirdExamDotNet.Context;
using ThirdExamDotNet.Models;

namespace ThirdExamDotNet.Controllers
{
    public class TowersController : Controller
    {
        private readonly ContextDb _context;

        public TowersController(ContextDb context)
        {
            _context = context;
        }

        // GET: Towers
        public async Task<IActionResult> Index()
        {
              return _context.Towers != null ? 
                          View(await _context.Towers.ToListAsync()) :
                          Problem("Entity set 'ContextDb.Towers'  is null.");
        }

        // GET: Towers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Towers == null)
            {
                return NotFound();
            }

            var tower = await _context.Towers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tower == null)
            {
                return NotFound();
            }

            return View(tower);
        }

        // GET: Towers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Towers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Zone")] Tower tower)
        {
            if (ModelState.IsValid)
            {
                tower.Id = Guid.NewGuid();
                _context.Add(tower);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tower);
        }

        // GET: Towers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Towers == null)
            {
                return NotFound();
            }

            var tower = await _context.Towers.FindAsync(id);
            if (tower == null)
            {
                return NotFound();
            }
            return View(tower);
        }

        // POST: Towers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Zone")] Tower tower)
        {
            if (id != tower.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tower);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TowerExists(tower.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tower);
        }

        // GET: Towers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Towers == null)
            {
                return NotFound();
            }

            var tower = await _context.Towers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tower == null)
            {
                return NotFound();
            }

            return View(tower);
        }

        // POST: Towers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Towers == null)
            {
                return Problem("Entity set 'ContextDb.Towers'  is null.");
            }
            var tower = await _context.Towers.FindAsync(id);
            if (tower != null)
            {
                _context.Towers.Remove(tower);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TowerExists(Guid id)
        {
          return (_context.Towers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ThirdExamDotNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>@ViewData["Title"] - ThirdExamDotNet</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/ThirdExamDotNet.styles.css" asp-append-version="true" />

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: Mar 09 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
    <partial name="_LoginPartial"/>

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>@ViewData["Title"]</h1>      
    </div><!-- End Page Title -->

    <section class="section dashboard">
      @RenderBody()
    </section>

  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>

ThirdExamDotNet/Views/Shared/_SideBar.cshtml
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "home" ? "" : "collapsed")" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Inicio</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "tower" ? "" : "collapsed")" asp-area="" asp-controller="Towers" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Torres</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "profession" ? "" : "collapsed")" asp-area="" asp-controller="Professions" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Profesiones</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "study_program" ? "" : "collapsed")" asp-area="" asp-controller="StudyPrograms" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Programas</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "instructor" ? "" : "collapsed")" asp-area="" asp-controller="Instructors" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Instructores</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "classroom" ? "" : "collapsed")" asp-area="" asp-controller="Classrooms" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Ambientes</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link @(ViewData["View"] == "student" ? "" : "collapsed")" asp-area="" asp-controller="Students" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Aprendices</span>
            </a>
        </li>
    </ul>
</aside>